// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	time "time"

	apioperatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	versioned "github.com/openshift/cert-manager-operator/pkg/operator/clientset/versioned"
	internalinterfaces "github.com/openshift/cert-manager-operator/pkg/operator/informers/externalversions/internalinterfaces"
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/pkg/operator/listers/operator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ApproverPolicyManagerInformer provides access to a shared informer and lister for
// ApproverPolicyManagers.
type ApproverPolicyManagerInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() operatorv1alpha1.ApproverPolicyManagerLister
}

type approverPolicyManagerInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewApproverPolicyManagerInformer constructs a new informer for ApproverPolicyManager type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewApproverPolicyManagerInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredApproverPolicyManagerInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredApproverPolicyManagerInformer constructs a new informer for ApproverPolicyManager type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredApproverPolicyManagerInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		cache.ToListWatcherWithWatchListSemantics(&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().ApproverPolicyManagers().List(context.Background(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().ApproverPolicyManagers().Watch(context.Background(), options)
			},
			ListWithContextFunc: func(ctx context.Context, options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().ApproverPolicyManagers().List(ctx, options)
			},
			WatchFuncWithContext: func(ctx context.Context, options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.OperatorV1alpha1().ApproverPolicyManagers().Watch(ctx, options)
			},
		}, client),
		&apioperatorv1alpha1.ApproverPolicyManager{},
		resyncPeriod,
		indexers,
	)
}

func (f *approverPolicyManagerInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredApproverPolicyManagerInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *approverPolicyManagerInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apioperatorv1alpha1.ApproverPolicyManager{}, f.defaultInformer)
}

func (f *approverPolicyManagerInformer) Lister() operatorv1alpha1.ApproverPolicyManagerLister {
	return operatorv1alpha1.NewApproverPolicyManagerLister(f.Informer().GetIndexer())
}
