// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	applyconfigurationsoperatorv1alpha1 "github.com/openshift/cert-manager-operator/pkg/operator/applyconfigurations/operator/v1alpha1"
	scheme "github.com/openshift/cert-manager-operator/pkg/operator/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ApproverPolicyManagersGetter has a method to return a ApproverPolicyManagerInterface.
// A group's client should implement this interface.
type ApproverPolicyManagersGetter interface {
	ApproverPolicyManagers() ApproverPolicyManagerInterface
}

// ApproverPolicyManagerInterface has methods to work with ApproverPolicyManager resources.
type ApproverPolicyManagerInterface interface {
	Create(ctx context.Context, approverPolicyManager *operatorv1alpha1.ApproverPolicyManager, opts v1.CreateOptions) (*operatorv1alpha1.ApproverPolicyManager, error)
	Update(ctx context.Context, approverPolicyManager *operatorv1alpha1.ApproverPolicyManager, opts v1.UpdateOptions) (*operatorv1alpha1.ApproverPolicyManager, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, approverPolicyManager *operatorv1alpha1.ApproverPolicyManager, opts v1.UpdateOptions) (*operatorv1alpha1.ApproverPolicyManager, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*operatorv1alpha1.ApproverPolicyManager, error)
	List(ctx context.Context, opts v1.ListOptions) (*operatorv1alpha1.ApproverPolicyManagerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *operatorv1alpha1.ApproverPolicyManager, err error)
	Apply(ctx context.Context, approverPolicyManager *applyconfigurationsoperatorv1alpha1.ApproverPolicyManagerApplyConfiguration, opts v1.ApplyOptions) (result *operatorv1alpha1.ApproverPolicyManager, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, approverPolicyManager *applyconfigurationsoperatorv1alpha1.ApproverPolicyManagerApplyConfiguration, opts v1.ApplyOptions) (result *operatorv1alpha1.ApproverPolicyManager, err error)
	ApproverPolicyManagerExpansion
}

// approverPolicyManagers implements ApproverPolicyManagerInterface
type approverPolicyManagers struct {
	*gentype.ClientWithListAndApply[*operatorv1alpha1.ApproverPolicyManager, *operatorv1alpha1.ApproverPolicyManagerList, *applyconfigurationsoperatorv1alpha1.ApproverPolicyManagerApplyConfiguration]
}

// newApproverPolicyManagers returns a ApproverPolicyManagers
func newApproverPolicyManagers(c *OperatorV1alpha1Client) *approverPolicyManagers {
	return &approverPolicyManagers{
		gentype.NewClientWithListAndApply[*operatorv1alpha1.ApproverPolicyManager, *operatorv1alpha1.ApproverPolicyManagerList, *applyconfigurationsoperatorv1alpha1.ApproverPolicyManagerApplyConfiguration](
			"approverpolicymanagers",
			c.RESTClient(),
			scheme.ParameterCodec,
			"",
			func() *operatorv1alpha1.ApproverPolicyManager { return &operatorv1alpha1.ApproverPolicyManager{} },
			func() *operatorv1alpha1.ApproverPolicyManagerList {
				return &operatorv1alpha1.ApproverPolicyManagerList{}
			},
		),
	}
}
