// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ApproverPolicyManagerExpansion interface{}

type CertManagerExpansion interface{}

type IstioCSRExpansion interface{}

type TrustManagerExpansion interface{}
