apiVersion: operator.openshift.io/v1alpha1
kind: TrustManager
metadata:
  labels:
    app.kubernetes.io/name: trustmanager
    app.kubernetes.io/part-of: cert-manager-operator
  name: cluster
spec:
  trustManagerConfig:
    logLevel: 1
    logFormat: text
    trustNamespace: cert-manager
