// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ApproverPolicyManagerLister helps list ApproverPolicyManagers.
// All objects returned here must be treated as read-only.
type ApproverPolicyManagerLister interface {
	// List lists all ApproverPolicyManagers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*operatorv1alpha1.ApproverPolicyManager, err error)
	// Get retrieves the ApproverPolicyManager from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*operatorv1alpha1.ApproverPolicyManager, error)
	ApproverPolicyManagerListerExpansion
}

// approverPolicyManagerLister implements the ApproverPolicyManagerLister interface.
type approverPolicyManagerLister struct {
	listers.ResourceIndexer[*operatorv1alpha1.ApproverPolicyManager]
}

// NewApproverPolicyManagerLister returns a new ApproverPolicyManagerLister.
func NewApproverPolicyManagerLister(indexer cache.Indexer) ApproverPolicyManagerLister {
	return &approverPolicyManagerLister{listers.New[*operatorv1alpha1.ApproverPolicyManager](indexer, operatorv1alpha1.Resource("approverpolicymanager"))}
}
