// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ApproverPolicyConfigApplyConfiguration represents a declarative configuration of the ApproverPolicyConfig type for use
// with apply.
//
// ApproverPolicyConfig configures the approver-policy operand's behavior.
type ApproverPolicyConfigApplyConfiguration struct {
	// logLevel configures the verbosity of approver-policy logging.
	LogLevel *int32 `json:"logLevel,omitempty"`
	// logFormat specifies the output format for approver-policy logging.
	// Supported formats are "text" and "json".
	LogFormat *string `json:"logFormat,omitempty"`
	// approveSignerNames is a list of signer names that approver-policy will be given
	// permission to approve and deny. CertificateRequests referencing these signer names
	// can be processed by approver-policy.
	//
	// When using approver-policy with external issuers, the external issuer signer names
	// MUST be included here so that approver-policy has permissions to approve and deny
	// CertificateRequests that reference them. If empty (default), approver-policy will have
	// permission to approve/deny CertificateRequests for ALL signers.
	//
	// This field can have a maximum of 50 entries.
	// Each entry can have a maximum of 825 characters.
	//
	// ref: https://cert-manager.io/docs/concepts/certificaterequest/#approval
	ApproveSignerNames []string `json:"approveSignerNames,omitempty"`
	// resources defines the compute resource requirements for the approver-policy pod.
	// ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
	Resources *v1.ResourceRequirements `json:"resources,omitempty"`
	// affinity defines scheduling constraints for the approver-policy pod.
	// ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
	Affinity *v1.Affinity `json:"affinity,omitempty"`
	// tolerations allows the approver-policy pod to be scheduled on tainted nodes.
	// This field can have a maximum of 50 entries.
	// ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
	Tolerations []v1.Toleration `json:"tolerations,omitempty"`
	// nodeSelector restricts which nodes the approver-policy pod can be scheduled on.
	// This field can have a maximum of 50 entries.
	// ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
	NodeSelector map[string]string `json:"nodeSelector,omitempty"`
}

// ApproverPolicyConfigApplyConfiguration constructs a declarative configuration of the ApproverPolicyConfig type for use with
// apply.
func ApproverPolicyConfig() *ApproverPolicyConfigApplyConfiguration {
	return &ApproverPolicyConfigApplyConfiguration{}
}

// WithLogLevel sets the LogLevel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogLevel field is set to the value of the last call.
func (b *ApproverPolicyConfigApplyConfiguration) WithLogLevel(value int32) *ApproverPolicyConfigApplyConfiguration {
	b.LogLevel = &value
	return b
}

// WithLogFormat sets the LogFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LogFormat field is set to the value of the last call.
func (b *ApproverPolicyConfigApplyConfiguration) WithLogFormat(value string) *ApproverPolicyConfigApplyConfiguration {
	b.LogFormat = &value
	return b
}

// WithApproveSignerNames adds the given value to the ApproveSignerNames field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ApproveSignerNames field.
func (b *ApproverPolicyConfigApplyConfiguration) WithApproveSignerNames(values ...string) *ApproverPolicyConfigApplyConfiguration {
	for i := range values {
		b.ApproveSignerNames = append(b.ApproveSignerNames, values[i])
	}
	return b
}

// WithResources sets the Resources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Resources field is set to the value of the last call.
func (b *ApproverPolicyConfigApplyConfiguration) WithResources(value v1.ResourceRequirements) *ApproverPolicyConfigApplyConfiguration {
	b.Resources = &value
	return b
}

// WithAffinity sets the Affinity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Affinity field is set to the value of the last call.
func (b *ApproverPolicyConfigApplyConfiguration) WithAffinity(value v1.Affinity) *ApproverPolicyConfigApplyConfiguration {
	b.Affinity = &value
	return b
}

// WithTolerations adds the given value to the Tolerations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tolerations field.
func (b *ApproverPolicyConfigApplyConfiguration) WithTolerations(values ...v1.Toleration) *ApproverPolicyConfigApplyConfiguration {
	for i := range values {
		b.Tolerations = append(b.Tolerations, values[i])
	}
	return b
}

// WithNodeSelector puts the entries into the NodeSelector field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the NodeSelector field,
// overwriting an existing map entries in NodeSelector field with the same key.
func (b *ApproverPolicyConfigApplyConfiguration) WithNodeSelector(entries map[string]string) *ApproverPolicyConfigApplyConfiguration {
	if b.NodeSelector == nil && len(entries) > 0 {
		b.NodeSelector = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.NodeSelector[k] = v
	}
	return b
}
