// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	internal "github.com/openshift/cert-manager-operator/pkg/operator/applyconfigurations/internal"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ApproverPolicyManagerApplyConfiguration represents a declarative configuration of the ApproverPolicyManager type for use
// with apply.
//
// ApproverPolicyManager describes the configuration and information about the managed approver-policy deployment.
// The name must be `cluster` to make ApproverPolicyManager a singleton, allowing only one instance per cluster.
//
// When an ApproverPolicyManager CR is created, approver-policy is deployed in the cert-manager namespace.
// The cert-manager operator automatically coordinates the transition: once the approver-policy operand
// is running and healthy (Ready=True), the cert-manager controller automatically disables the built-in
// CertificateRequest auto-approver to prevent racing conditions.
//
// When the ApproverPolicyManager CR is deleted, all operator-created resources are cleaned up and the
// built-in cert-manager auto-approver is automatically re-enabled.
type ApproverPolicyManagerApplyConfiguration struct {
	v1.TypeMetaApplyConfiguration `json:",inline"`
	// metadata is the standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	*v1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	// spec is the specification of the desired behavior of the ApproverPolicyManager.
	Spec *ApproverPolicyManagerSpecApplyConfiguration `json:"spec,omitempty"`
	// status is the most recently observed status of the ApproverPolicyManager.
	Status *ApproverPolicyManagerStatusApplyConfiguration `json:"status,omitempty"`
}

// ApproverPolicyManager constructs a declarative configuration of the ApproverPolicyManager type for use with
// apply.
func ApproverPolicyManager(name string) *ApproverPolicyManagerApplyConfiguration {
	b := &ApproverPolicyManagerApplyConfiguration{}
	b.WithName(name)
	b.WithKind("ApproverPolicyManager")
	b.WithAPIVersion("operator.openshift.io/v1alpha1")
	return b
}

// ExtractApproverPolicyManagerFrom extracts the applied configuration owned by fieldManager from
// approverPolicyManager for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// approverPolicyManager must be a unmodified ApproverPolicyManager API object that was retrieved from the Kubernetes API.
// ExtractApproverPolicyManagerFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractApproverPolicyManagerFrom(approverPolicyManager *operatorv1alpha1.ApproverPolicyManager, fieldManager string, subresource string) (*ApproverPolicyManagerApplyConfiguration, error) {
	b := &ApproverPolicyManagerApplyConfiguration{}
	err := managedfields.ExtractInto(approverPolicyManager, internal.Parser().Type("com.github.openshift.cert-manager-operator.api.operator.v1alpha1.ApproverPolicyManager"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(approverPolicyManager.Name)

	b.WithKind("ApproverPolicyManager")
	b.WithAPIVersion("operator.openshift.io/v1alpha1")
	return b, nil
}

// ExtractApproverPolicyManager extracts the applied configuration owned by fieldManager from
// approverPolicyManager. If no managedFields are found in approverPolicyManager for fieldManager, a
// ApproverPolicyManagerApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// approverPolicyManager must be a unmodified ApproverPolicyManager API object that was retrieved from the Kubernetes API.
// ExtractApproverPolicyManager provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractApproverPolicyManager(approverPolicyManager *operatorv1alpha1.ApproverPolicyManager, fieldManager string) (*ApproverPolicyManagerApplyConfiguration, error) {
	return ExtractApproverPolicyManagerFrom(approverPolicyManager, fieldManager, "")
}

// ExtractApproverPolicyManagerStatus extracts the applied configuration owned by fieldManager from
// approverPolicyManager for the status subresource.
func ExtractApproverPolicyManagerStatus(approverPolicyManager *operatorv1alpha1.ApproverPolicyManager, fieldManager string) (*ApproverPolicyManagerApplyConfiguration, error) {
	return ExtractApproverPolicyManagerFrom(approverPolicyManager, fieldManager, "status")
}

func (b ApproverPolicyManagerApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithKind(value string) *ApproverPolicyManagerApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithAPIVersion(value string) *ApproverPolicyManagerApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithName(value string) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithGenerateName(value string) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithNamespace(value string) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithUID(value types.UID) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithResourceVersion(value string) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithGeneration(value int64) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithCreationTimestamp(value metav1.Time) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithDeletionTimestamp(value metav1.Time) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ApproverPolicyManagerApplyConfiguration) WithLabels(entries map[string]string) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ApproverPolicyManagerApplyConfiguration) WithAnnotations(entries map[string]string) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *ApproverPolicyManagerApplyConfiguration) WithOwnerReferences(values ...*v1.OwnerReferenceApplyConfiguration) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *ApproverPolicyManagerApplyConfiguration) WithFinalizers(values ...string) *ApproverPolicyManagerApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *ApproverPolicyManagerApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &v1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithSpec(value *ApproverPolicyManagerSpecApplyConfiguration) *ApproverPolicyManagerApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ApproverPolicyManagerApplyConfiguration) WithStatus(value *ApproverPolicyManagerStatusApplyConfiguration) *ApproverPolicyManagerApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *ApproverPolicyManagerApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *ApproverPolicyManagerApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *ApproverPolicyManagerApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *ApproverPolicyManagerApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
