// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
)

// ApproverPolicyWebhookConfigApplyConfiguration represents a declarative configuration of the ApproverPolicyWebhookConfig type for use
// with apply.
//
// ApproverPolicyWebhookConfig configures the approver-policy integration for
// trust-manager's webhook TLS certificate.
type ApproverPolicyWebhookConfigApplyConfiguration struct {
	// enabled controls whether to create a CertificateRequestPolicy and RBAC
	// resources that allow approver-policy to approve trust-manager's webhook
	// TLS certificate.
	//
	// Enabled: The operator creates a CertificateRequestPolicy, ClusterRole, and
	// ClusterRoleBinding. The ClusterRoleBinding is bound to the cert-manager
	// ServiceAccount (always "cert-manager" in the "cert-manager" namespace --
	// hardcoded by the operator, not configurable).
	//
	// Disabled (default): No policy or RBAC resources are created. If this field is
	// flipped from Enabled to Disabled, any previously created CertificateRequestPolicy,
	// ClusterRole, and ClusterRoleBinding are deleted.
	//
	// Resources are managed solely based on this field value -- no dependency on
	// ApproverPolicyManager CR status, Deployment availability, or approveSignerNames.
	Enabled *operatorv1alpha1.ApproverPolicyWebhookPolicy `json:"enabled,omitempty"`
}

// ApproverPolicyWebhookConfigApplyConfiguration constructs a declarative configuration of the ApproverPolicyWebhookConfig type for use with
// apply.
func ApproverPolicyWebhookConfig() *ApproverPolicyWebhookConfigApplyConfiguration {
	return &ApproverPolicyWebhookConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ApproverPolicyWebhookConfigApplyConfiguration) WithEnabled(value operatorv1alpha1.ApproverPolicyWebhookPolicy) *ApproverPolicyWebhookConfigApplyConfiguration {
	b.Enabled = &value
	return b
}
