// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ApproverPolicyControllerConfigApplyConfiguration represents a declarative configuration of the ApproverPolicyControllerConfig type for use
// with apply.
//
// ApproverPolicyControllerConfig configures the operator's behavior for
// creating approver-policy resources.
type ApproverPolicyControllerConfigApplyConfiguration struct {
	// labels to apply to all resources created for the approver-policy deployment.
	// These labels are in addition to the default labels added by the operator.
	// This field can have a maximum of 20 entries.
	Labels map[string]string `json:"labels,omitempty"`
	// annotations to apply to all resources created for the approver-policy deployment.
	// This field can have a maximum of 20 entries.
	Annotations map[string]string `json:"annotations,omitempty"`
}

// ApproverPolicyControllerConfigApplyConfiguration constructs a declarative configuration of the ApproverPolicyControllerConfig type for use with
// apply.
func ApproverPolicyControllerConfig() *ApproverPolicyControllerConfigApplyConfiguration {
	return &ApproverPolicyControllerConfigApplyConfiguration{}
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ApproverPolicyControllerConfigApplyConfiguration) WithLabels(entries map[string]string) *ApproverPolicyControllerConfigApplyConfiguration {
	if b.Labels == nil && len(entries) > 0 {
		b.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ApproverPolicyControllerConfigApplyConfiguration) WithAnnotations(entries map[string]string) *ApproverPolicyControllerConfigApplyConfiguration {
	if b.Annotations == nil && len(entries) > 0 {
		b.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.Annotations[k] = v
	}
	return b
}
