// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ApproverPolicyManagerStatusApplyConfiguration represents a declarative configuration of the ApproverPolicyManagerStatus type for use
// with apply.
//
// ApproverPolicyManagerStatus defines the observed state of ApproverPolicyManager.
// The status is updated by the operator during each reconciliation.
type ApproverPolicyManagerStatusApplyConfiguration struct {
	// conditions holds information about the current state of the approver-policy deployment.
	// Standard conditions include:
	// - Ready: True when approver-policy is fully operational
	// - Degraded: True when there's an issue affecting functionality
	// - Progressing: True when changes are being applied
	ConditionalStatusApplyConfiguration `json:",omitempty,inline"`
	// approverPolicyImage is the container image (name:tag) used for approver-policy.
	// This is populated from the RELATED_IMAGE_APPROVER_POLICY environment variable.
	ApproverPolicyImage *string `json:"approverPolicyImage,omitempty"`
}

// ApproverPolicyManagerStatusApplyConfiguration constructs a declarative configuration of the ApproverPolicyManagerStatus type for use with
// apply.
func ApproverPolicyManagerStatus() *ApproverPolicyManagerStatusApplyConfiguration {
	return &ApproverPolicyManagerStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ApproverPolicyManagerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *ApproverPolicyManagerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.ConditionalStatusApplyConfiguration.Conditions = append(b.ConditionalStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithApproverPolicyImage sets the ApproverPolicyImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ApproverPolicyImage field is set to the value of the last call.
func (b *ApproverPolicyManagerStatusApplyConfiguration) WithApproverPolicyImage(value string) *ApproverPolicyManagerStatusApplyConfiguration {
	b.ApproverPolicyImage = &value
	return b
}
