// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DefaultCAPackageStatusApplyConfiguration represents a declarative configuration of the DefaultCAPackageStatus type for use
// with apply.
type DefaultCAPackageStatusApplyConfiguration struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// DefaultCAPackageStatusApplyConfiguration constructs a declarative configuration of the DefaultCAPackageStatus type for use with
// apply.
func DefaultCAPackageStatus() *DefaultCAPackageStatusApplyConfiguration {
	return &DefaultCAPackageStatusApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *DefaultCAPackageStatusApplyConfiguration) WithEnabled(value bool) *DefaultCAPackageStatusApplyConfiguration {
	b.Enabled = &value
	return b
}
