// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DefaultCAPackageConfigApplyConfiguration represents a declarative configuration of the DefaultCAPackageConfig type for use
// with apply.
type DefaultCAPackageConfigApplyConfiguration struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// DefaultCAPackageConfigApplyConfiguration constructs a declarative configuration of the DefaultCAPackageConfig type for use with
// apply.
func DefaultCAPackageConfig() *DefaultCAPackageConfigApplyConfiguration {
	return &DefaultCAPackageConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *DefaultCAPackageConfigApplyConfiguration) WithEnabled(value bool) *DefaultCAPackageConfigApplyConfiguration {
	b.Enabled = &value
	return b
}
