// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SecretTargetsConfigApplyConfiguration represents a declarative configuration of the SecretTargetsConfig type for use
// with apply.
type SecretTargetsConfigApplyConfiguration struct {
	Enabled              *bool    `json:"enabled,omitempty"`
	AuthorizedSecretsAll *bool    `json:"authorizedSecretsAll,omitempty"`
	AuthorizedSecrets    []string `json:"authorizedSecrets,omitempty"`
}

// SecretTargetsConfigApplyConfiguration constructs a declarative configuration of the SecretTargetsConfig type for use with
// apply.
func SecretTargetsConfig() *SecretTargetsConfigApplyConfiguration {
	return &SecretTargetsConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *SecretTargetsConfigApplyConfiguration) WithEnabled(value bool) *SecretTargetsConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithAuthorizedSecretsAll sets the AuthorizedSecretsAll field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AuthorizedSecretsAll field is set to the value of the last call.
func (b *SecretTargetsConfigApplyConfiguration) WithAuthorizedSecretsAll(value bool) *SecretTargetsConfigApplyConfiguration {
	b.AuthorizedSecretsAll = &value
	return b
}

// WithAuthorizedSecrets adds the given value to the AuthorizedSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AuthorizedSecrets field.
func (b *SecretTargetsConfigApplyConfiguration) WithAuthorizedSecrets(values ...string) *SecretTargetsConfigApplyConfiguration {
	for i := range values {
		b.AuthorizedSecrets = append(b.AuthorizedSecrets, values[i])
	}
	return b
}
