// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// TrustManagerStatusApplyConfiguration represents a declarative configuration of the TrustManagerStatus type for use
// with apply.
type TrustManagerStatusApplyConfiguration struct {
	ConditionalStatusApplyConfiguration `json:",omitempty,inline"`
	TrustManagerImage                   *string `json:"trustManagerImage,omitempty"`
	ServiceAccount                      *string `json:"serviceAccount,omitempty"`
	ClusterRole                         *string `json:"clusterRole,omitempty"`
	ClusterRoleBinding                  *string `json:"clusterRoleBinding,omitempty"`
	SecretTargetsEnabled                *bool   `json:"secretTargetsEnabled,omitempty"`
}

// TrustManagerStatusApplyConfiguration constructs a declarative configuration of the TrustManagerStatus type for use with
// apply.
func TrustManagerStatus() *TrustManagerStatusApplyConfiguration {
	return &TrustManagerStatusApplyConfiguration{}
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *TrustManagerStatusApplyConfiguration) WithConditions(values ...*v1.ConditionApplyConfiguration) *TrustManagerStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.ConditionalStatusApplyConfiguration.Conditions = append(b.ConditionalStatusApplyConfiguration.Conditions, *values[i])
	}
	return b
}

// WithTrustManagerImage sets the TrustManagerImage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TrustManagerImage field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithTrustManagerImage(value string) *TrustManagerStatusApplyConfiguration {
	b.TrustManagerImage = &value
	return b
}

// WithServiceAccount sets the ServiceAccount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccount field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithServiceAccount(value string) *TrustManagerStatusApplyConfiguration {
	b.ServiceAccount = &value
	return b
}

// WithClusterRole sets the ClusterRole field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRole field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithClusterRole(value string) *TrustManagerStatusApplyConfiguration {
	b.ClusterRole = &value
	return b
}

// WithClusterRoleBinding sets the ClusterRoleBinding field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterRoleBinding field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithClusterRoleBinding(value string) *TrustManagerStatusApplyConfiguration {
	b.ClusterRoleBinding = &value
	return b
}

// WithSecretTargetsEnabled sets the SecretTargetsEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretTargetsEnabled field is set to the value of the last call.
func (b *TrustManagerStatusApplyConfiguration) WithSecretTargetsEnabled(value bool) *TrustManagerStatusApplyConfiguration {
	b.SecretTargetsEnabled = &value
	return b
}
