// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/openshift/cert-manager-operator/api/operator/v1alpha1"
	operatorv1alpha1 "github.com/openshift/cert-manager-operator/pkg/operator/applyconfigurations/operator/v1alpha1"
	typedoperatorv1alpha1 "github.com/openshift/cert-manager-operator/pkg/operator/clientset/versioned/typed/operator/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeApproverPolicyManagers implements ApproverPolicyManagerInterface
type fakeApproverPolicyManagers struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.ApproverPolicyManager, *v1alpha1.ApproverPolicyManagerList, *operatorv1alpha1.ApproverPolicyManagerApplyConfiguration]
	Fake *FakeOperatorV1alpha1
}

func newFakeApproverPolicyManagers(fake *FakeOperatorV1alpha1) typedoperatorv1alpha1.ApproverPolicyManagerInterface {
	return &fakeApproverPolicyManagers{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.ApproverPolicyManager, *v1alpha1.ApproverPolicyManagerList, *operatorv1alpha1.ApproverPolicyManagerApplyConfiguration](
			fake.Fake,
			"",
			v1alpha1.SchemeGroupVersion.WithResource("approverpolicymanagers"),
			v1alpha1.SchemeGroupVersion.WithKind("ApproverPolicyManager"),
			func() *v1alpha1.ApproverPolicyManager { return &v1alpha1.ApproverPolicyManager{} },
			func() *v1alpha1.ApproverPolicyManagerList { return &v1alpha1.ApproverPolicyManagerList{} },
			func(dst, src *v1alpha1.ApproverPolicyManagerList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.ApproverPolicyManagerList) []*v1alpha1.ApproverPolicyManager {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.ApproverPolicyManagerList, items []*v1alpha1.ApproverPolicyManager) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
