apiVersion: operator.openshift.io/v1alpha1
kind: CertManager
metadata:
  name: cluster
spec:
  managementState: Managed
  logLevel: Normal
  unsupportedConfigOverrides:
    controller:
      args:
        - "--concurrent-workers=10"
        - "--kube-api-qps=50"
        - "--kube-api-burst=100"
        - "--max-concurrent-challenges=120"
    webhook:
      args: []
    cainjector:
      args: []
  controllerConfig:
    overrideResources:
      requests:
        cpu: "500m"
        memory: "256Mi"
      limits:
        cpu: "2000m"
        memory: "1Gi"
